/* 
 * Copyright 2015 Igor Maznitsa (http://www.igormaznitsa.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.igormaznitsa.jjjvm.stubgen.jjjvmwrapper;

import com.igormaznitsa.jjjvm.stubgen.jjjvmwrapper.model.ClassItem;
import javax.swing.DefaultComboBoxModel;
import org.apache.bcel.classfile.JavaClass;

public class ClassItemProperties extends javax.swing.JPanel
{

    public static final long serialVersionUID = 8732921873l;

    /** Creates new form ClassItemProperties */
    public ClassItemProperties()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelPackage = new javax.swing.JLabel();
    textFieldPackage = new javax.swing.JTextField();
    labelClassName = new javax.swing.JLabel();
    textFieldClassName = new javax.swing.JTextField();
    panelMethods = new javax.swing.JScrollPane();
    listMethods = new javax.swing.JList();
    panelFields = new javax.swing.JScrollPane();
    listFields = new javax.swing.JList();
    labelSuperclass = new javax.swing.JLabel();
    textFieldSuperclass = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    panwlVisibility = new javax.swing.JPanel();
    checkboxPublic = new javax.swing.JCheckBox();
    checkboxFinal = new javax.swing.JCheckBox();
    checkboxSuper = new javax.swing.JCheckBox();
    checkboxInterface = new javax.swing.JCheckBox();
    checkboxAbstract = new javax.swing.JCheckBox();
    checkboxStrictFP = new javax.swing.JCheckBox();
    panelInterfaces = new javax.swing.JScrollPane();
    listInterfaces = new javax.swing.JList();
    labelCompilerVersion = new javax.swing.JLabel();
    textFieldCompilerVersion = new javax.swing.JTextField();

    labelPackage.setText("Package:");

    textFieldPackage.setEditable(false);
    textFieldPackage.setDisabledTextColor(new java.awt.Color(0, 0, 0));

    labelClassName.setText("Class name:");

    textFieldClassName.setEditable(false);
    textFieldClassName.setDisabledTextColor(new java.awt.Color(0, 0, 0));

    panelMethods.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Methods"));

    listMethods.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    listMethods.setEnabled(false);
    panelMethods.setViewportView(listMethods);

    panelFields.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fields"));

    listFields.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    listFields.setEnabled(false);
    panelFields.setViewportView(listFields);

    labelSuperclass.setText("Superclass:");

    textFieldSuperclass.setEditable(false);
    textFieldSuperclass.setDisabledTextColor(new java.awt.Color(0, 0, 0));

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    panwlVisibility.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Visibility"));

    checkboxPublic.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    checkboxPublic.setText("Public");
    checkboxPublic.setEnabled(false);

    checkboxFinal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    checkboxFinal.setText("Final");
    checkboxFinal.setEnabled(false);

    checkboxSuper.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    checkboxSuper.setText("Super");
    checkboxSuper.setEnabled(false);

    checkboxInterface.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    checkboxInterface.setText("Interface");
    checkboxInterface.setEnabled(false);

    checkboxAbstract.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    checkboxAbstract.setText("Abstract");
    checkboxAbstract.setEnabled(false);

    checkboxStrictFP.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    checkboxStrictFP.setText("StrictFP");
    checkboxStrictFP.setEnabled(false);

    javax.swing.GroupLayout panwlVisibilityLayout = new javax.swing.GroupLayout(panwlVisibility);
    panwlVisibility.setLayout(panwlVisibilityLayout);
    panwlVisibilityLayout.setHorizontalGroup(
      panwlVisibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panwlVisibilityLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panwlVisibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(checkboxPublic)
          .addComponent(checkboxSuper)
          .addComponent(checkboxAbstract))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
        .addGroup(panwlVisibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(checkboxFinal)
          .addComponent(checkboxInterface)
          .addComponent(checkboxStrictFP))
        .addContainerGap(44, Short.MAX_VALUE))
    );
    panwlVisibilityLayout.setVerticalGroup(
      panwlVisibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panwlVisibilityLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panwlVisibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(checkboxPublic)
          .addComponent(checkboxFinal))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panwlVisibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(checkboxSuper)
          .addComponent(checkboxInterface))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panwlVisibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(checkboxAbstract)
          .addComponent(checkboxStrictFP))
        .addContainerGap(10, Short.MAX_VALUE))
    );

    panelInterfaces.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Implemented interfaces"));

    listInterfaces.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    listInterfaces.setEnabled(false);
    panelInterfaces.setViewportView(listInterfaces);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(panwlVisibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelInterfaces, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(panwlVisibility, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelInterfaces, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
        .addContainerGap())
    );

    labelCompilerVersion.setText("Compiler version:");

    textFieldCompilerVersion.setEditable(false);
    textFieldCompilerVersion.setDisabledTextColor(new java.awt.Color(0, 0, 0));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelSuperclass, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(labelClassName, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(labelPackage, javax.swing.GroupLayout.Alignment.TRAILING))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(textFieldPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(labelCompilerVersion)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textFieldCompilerVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(textFieldClassName, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
          .addComponent(textFieldSuperclass, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(panelFields, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelMethods, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(7, 7, 7))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(textFieldPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelPackage)
          .addComponent(labelCompilerVersion)
          .addComponent(textFieldCompilerVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(textFieldClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelClassName))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(textFieldSuperclass)
          .addComponent(labelSuperclass))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelMethods, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
          .addComponent(panelFields, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkboxAbstract;
  private javax.swing.JCheckBox checkboxFinal;
  private javax.swing.JCheckBox checkboxInterface;
  private javax.swing.JCheckBox checkboxPublic;
  private javax.swing.JCheckBox checkboxStrictFP;
  private javax.swing.JCheckBox checkboxSuper;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel labelClassName;
  private javax.swing.JLabel labelCompilerVersion;
  private javax.swing.JLabel labelPackage;
  private javax.swing.JLabel labelSuperclass;
  private javax.swing.JList listFields;
  private javax.swing.JList listInterfaces;
  private javax.swing.JList listMethods;
  private javax.swing.JScrollPane panelFields;
  private javax.swing.JScrollPane panelInterfaces;
  private javax.swing.JScrollPane panelMethods;
  private javax.swing.JPanel panwlVisibility;
  private javax.swing.JTextField textFieldClassName;
  private javax.swing.JTextField textFieldCompilerVersion;
  private javax.swing.JTextField textFieldPackage;
  private javax.swing.JTextField textFieldSuperclass;
  // End of variables declaration//GEN-END:variables

    public void setModel(final ClassItem classItem)
    {
        this.checkboxAbstract.setSelected(false);
        this.checkboxFinal.setSelected(false);
        this.checkboxInterface.setSelected(false);
        this.checkboxPublic.setSelected(false);
        this.checkboxSuper.setSelected(false);
        this.checkboxStrictFP.setSelected(false);

        this.textFieldClassName.setText("");
        this.textFieldCompilerVersion.setText("");
        this.textFieldPackage.setText("");
        this.textFieldSuperclass.setText("");

        this.listInterfaces.removeAll();
        this.listMethods.removeAll();
        this.listFields.removeAll();

        if (classItem != null)
        {
            final JavaClass jclazz = classItem.getJavaClass();
            this.checkboxAbstract.setSelected(jclazz.isAbstract());
            this.checkboxFinal.setSelected(jclazz.isFinal());
            this.checkboxInterface.setSelected(jclazz.isInterface());
            this.checkboxPublic.setSelected(jclazz.isPublic());
            this.checkboxSuper.setSelected(jclazz.isSuper());
            this.checkboxStrictFP.setSelected(jclazz.isStrictfp());

            this.listFields.setModel(new DefaultComboBoxModel(jclazz.getFields()));
            this.listMethods.setModel(new DefaultComboBoxModel(jclazz.getMethods()));
            this.listInterfaces.setModel(new DefaultComboBoxModel(jclazz.getInterfaceNames()));

            this.textFieldCompilerVersion.setText(jclazz.getMajor()+"."+jclazz.getMinor());
            this.textFieldClassName.setText(jclazz.getClassName());
            this.textFieldSuperclass.setText(jclazz.getSuperclassName());
            this.textFieldPackage.setText(jclazz.getPackageName());
        }

    }
}
